language: python
python:
  - "3.6"
install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - pipenv install coveralls
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - pytest
after_success:
  - coveralls