dist: xenial

language: python

python:
  - "3.6"

install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - pipenv install coveralls

addons:
  firefox: latest

script:

  - python purbeurre/manage.py migrate
  - pytest purbeurre/

after_success:
  - coveralls