dist: xenial

language: python

python:
  - "3.6"

install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - pipenv install coveralls

script:

  - python purbeurre/manage.py migrate
  - purbeurre/pytest

after_success:
  - coveralls