language: python

python:
  - "3.6"

services: postgresql

install:
  - 'pip install pipenv'
  - 'pipenv sync'
  - pipenv install coveralls

before_script:
  - psql -c "CREATE DATABASE travisdb;" -U postgres

script:

  - python purbeurre/manage.py migrate
  - pytest

after_success:
  - coveralls