# Generated by Django 2.2 on 2019-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190428_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fat_100g',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100g',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_100g',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
